# Generated by Django 2.2.10 on 2021-02-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manager',
            new_name='manage',
        ),
    ]
